#pragma once

#include "keyboard.h"

enum layers {
    _BASE    = 0,
    _FINGERS = COMBO_ONLY_FROM_LAYER,
    _SYMBOLS,
    _NUMBERS,
    _NAVIGATION,
    _SYSTEM,
    _LEFT_MOD,
    _RIGHT_MOD,
};

enum my_keycodes {
    FINGERS_START = SAFE_RANGE,
#define FINGERS_MACRO(...) __VA_ARGS__,
#include "fingers.def"
#undef FINGERS_MACRO
    FINGERS_END,

    LAYER_LOCK,
};

/* ADDITIONAL KEYS */

#define MY_DOT KC_DOT
#define MY_COMMA KC_COMMA
#define MY_DASH KC_MINUS
#define MY_LINE KC_UNDERSCORE
#define MY_PERCENT KC_PERCENT
#define MY_PLUS KC_PLUS
#define MY_EQUAL KC_EQUAL
#define MY_BOOL KC_AMPERSAND
#define MY_REGEX KC_DOLLAR
#define MY_HASH KC_HASH
#define MY_PAREN KC_LEFT_PAREN
#define MY_SQUARE KC_LEFT_BRACKET
#define MY_CURLY KC_LEFT_CURLY_BRACE
#define MY_ANGLE KC_LEFT_ANGLE_BRACKET

#define MY_RALT KC_LALT

#define MY_ROCKET KC_F18
#define MY_MAGIC KC_F19

#define MO_SYM MO(_SYMBOLS)
#define MO_NUM MO(_NUMBERS)
#define MO_NAV MO(_NAVIGATION)
#define MO_SYS MO(_SYSTEM)

#define MEDIA_LEFT KC_MEDIA_PREV_TRACK
#define MEDIA KC_MEDIA_PLAY_PAUSE
#define MEDIA_RIGHT KC_MEDIA_NEXT_TRACK

#define SYS_UP KC_F14
#define SYS_DOWN KC_F15
#define SYS_LEFT KC_F16
#define SYS_RIGHT KC_F17
#define SYS_HOME KC_F20
#define SYS_END KC_F21
